worker_processes  auto;

error_log /var/log/nginx/error.log notice;
pid        /tmp/nginx.pid;


events {
    worker_connections  1024;
}


http {
    proxy_temp_path /tmp/proxy_temp;
    client_body_temp_path /tmp/client_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    # Configura IP real do cliente
    set_real_ip_from  192.168.208.0/20;     # IP range of trusted proxy
    real_ip_header    X-Forwarded-For;    # Use this header to get the real client IP
    real_ip_recursive on;                # Trust the first non-trusted IP in the header

    access_log /var/log/nginx/access.log main;

    sendfile        on;
    tcp_nopush     on;
    tcp_nodelay on;
    keepalive_timeout 15;
    types_hash_max_size 2048;
    server_tokens off;

    # Limita requisições para evitar DoS leves
    # limit_conn_zone $binary_remote_addr zone=conn_limit:10m;
    # limit_conn conn_limit 10;

    # limit_req_zone $binary_remote_addr zone=rate_limit:10m rate=60r/s;
    # limit_req zone=rate_limit burst=70 nodelay;

    #gzip  on;

    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    include /etc/nginx/conf.d/*.conf;
}
