[PHP]
; Esconde versão do PHP
expose_php = Off

; Não mostrar erros ao usuário final
display_errors = Off
log_errors = On
# error_log = /var/log/php-fpm/php-error.log

; Limita upload de arquivos
file_uploads = On
upload_max_filesize = 10M
post_max_size = 12M
max_file_uploads = 5

variables_order = EGPCS
memory_limit = 2G

; Evita execução de código em uploads
# open_basedir = /var/www/:/tmp/

; Restringe funções críticas
# disable_functions = exec,passthru,shell_exec,system,proc_open,popen,curl_exec,curl_multi_exec,parse_ini_file,show_source

; Previne session hijacking
session.cookie_httponly = 1
session.cookie_secure = 1
session.use_strict_mode = 1

[opcache]
opcache.enable_cli = 1
